# Generated by Django 5.2.1 on 2025-08-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the base model', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the model', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='The user-entered run_id', max_length=255)),
                ('month', models.CharField(default='2025-07', max_length=20)),
                ('customer_count', models.IntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.basemodel')),
            ],
            options={
                'unique_together': {('base_model', 'run_id')},
            },
        ),
    ]
