# Generated by Django 5.2.5 on 2025-08-10 12:00

from django.db import migrations

def create_initial_models(apps, schema_editor):
    BaseModel = apps.get_model('core', 'BaseModel')
    BaseModel.objects.create(name='AML_Model_v3', description='Standard model for retail banking.')
    BaseModel.objects.create(name='AML_Model_v4_Corporate', description='Advanced model for corporate clients.')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_models),
    ]