# Generated by Django 5.2.5 on 2025-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_base_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='country',
            field=models.CharField(default='uk', help_text='Country code, e.g., uk/hk/mx/sg', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='analysisrun',
            unique_together={('base_model', 'run_id', 'country')},
        ),
    ]
